version: '3.8'

services:
  db:
    image: postgres:15
    container_name: hotel_postgres
    environment:
      POSTGRES_DB: hotel_db
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: "1111"
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  app:
    build: .
    container_name: hotel_app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: hotel_db
      DB_USER: hotel_user
      DB_PASSWORD: "1111"
    ports:
      - "8080:8080"

volumes:
  postgres_data:
